name: Check JSON & Ping Cronitor

on:
  schedule:
    - cron: "*/15 * * * *"  # alle 15 Minuten
  workflow_dispatch:        # manuelles Auslösen möglich

jobs:
  json-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Run Cronitor JSON Check
        run: node scripts/cronitor-json-check.js
